Chore/0 all rollback
IN-SOPT-ANDROID/sehun-kim pull request #12
Opened 2022-11-11 08:40 UTC by s9hn

## 📑view - viewModel 분리 Refactoring 중 입니다...
### [SignUp] State : done

- [✔] [SignUpActivity.xml] two-way dataBinding 세팅
- [✔] [SignUpActivity.kt] 뷰모델과 코드 분리
- [✔] [SignUpViewModel] 뷰와 코드 분리
- [✔] [SignUpViewModel] coroutine을 이용한 서버통신 구현

2022-11-11 14:13 UTC, IslandofDream approved these changes
리뷰 완!

2022-11-11 14:13 UTC, IslandofDream commented on app/src/main/java/org/sopt/sample/presentation/login/signup/SignUpActivity.kt
> +                SignUpMessage.SIGNUP_SUCCESS.message -> root.snackBar(stateMessage)
Enum 타입 활용 되게 좋네요!!

2022-11-11 14:13 UTC, IslandofDream commented on app/src/main/java/org/sopt/sample/presentation/login/signup/SignUpViewModel.kt
> +        viewModelScope.launch { // dispatcher
개인적으로는  내부 postSignUp suspend가 있어서 안붙어도 될거 같긴합니다

2022-11-16 14:45 UTC, jinsu4755 requested changes
항상 열심히 질문하고 꾸준하게 알아가려고 노력하는 모습에 리뷰 남기고 갑니다~ 활동기수가 아니라 리뷰 남기는게 상당히 머쓱하긴 하네...ㅋㅋㅋ

리뷰는 일단 아키택처 라던가 레이어의 분리라는 초점은 싹 빼고 남겨두긴 했는데 추후에 가능하다면 보다 좋은 상태의 아키택쳐와 레이어 분리를 진행해 보는것을 추천할께

지금 상태에서는 형이 항상 질문할 때마다 내가 답변하던 것과 같이 객체를 지향하는 코드를 만드는데 조금 더 익숙해지는 방향으로 가면 확실히 더 깔끔하고 좋은 코드가 될 수 있을 것 같아 :)

그리고 현재는 LiveData를 더 잘 이용하여 뷰에 상태값과 이벤트를 바인딩하는 행위를 Binding 레이어에 옮겨서 보다 뷰와 뷰모델 사이의 결합을 약하게 만들면 더 좋을 것 같아

과제에는 Request changes 잘 안 남기지만 리뷰 남긴 내용 중 꼭 한번 확인하고 적용해보면 좋을 것 같은 내용이 있어서 Reqeust Changes 남기고 갑니다! 나중에 리뷰 필요하면 또 이야기해줘~

2022-11-16 14:45 UTC, jinsu4755 commented on app/src/main/java/org/sopt/sample/presentation/login/signup/SignUpViewModel.kt
> +                        name.value!!
코틀린이 nullable 타입을 적용한 것은 java 에서 발생하는 NPE 를 쉽게 피하기 보다 보다 오히려 값이 없을 때 null을 적극 사용하여 명확하고 안전하게 다루기 위해 도입되었습니다.
해당 부분에서 사용한 Not-null Statements 의 경우는 null 값을 명확하고 안전하게 다룰 수 있는 방법이기 보다 오히려 null 일때 NPE 를 발생시킬  수 있습니다.
back-end 에 Null or Blank String 을 전달하면 안되는 상황이라면, 보다 명확하고 안전하게 처리할 수 있는 방법이 있지 않을까요?

2022-11-16 14:45 UTC, jinsu4755 commented on app/src/main/java/org/sopt/sample/presentation/login/signup/SignUpViewModel.kt
> +                        name.value!!
Elvis Statements 를 이용한 throw 도 하나의 방법이겠지만, 설계 구조에 있어서 애초에 요청에 null 이 들어가면 안되는 Value 라면 Runtime 에 Exception 을 던지기 보다 Compile Time 에 애초에 null 이 들어갈 수 없도록 구성해보는 것이 더 좋을 것 같습니다.

2022-11-16 14:45 UTC, jinsu4755 commented on app/src/main/java/org/sopt/sample/presentation/login/signup/SignUpViewModel.kt
> +    }
클린 코드를 위해서 else-if 와 else 를 피하라는 이야기가 있습니다. 해당 부분을 Early Return 하는 방식을 사용해 보는 것은 어떨까요?
또한 checkSignUpInput 이라는 회원가입 입력에 대한 검증 과정에서
- 이메일, 비밀번호, 이름이 null or Blank 인지 확인한다.
- 이메일에는 @가 포함되는지 확인한다.
- 비밀번호의 길이가 8을 넘지 않는지 확인한다.

라는 3가지의 검증 역할이 포함된 것 같습니다. 
긴 조건의 경우 가독성 및 추후 확장성, 혹은 재 사용을 고려해 분리해보면 더 좋을 것 같습니다.

2022-11-16 14:45 UTC, jinsu4755 commented on app/src/main/java/org/sopt/sample/presentation/login/signup/SignUpViewModel.kt
> +    }
또한 부정 조건을 피하라는 말은 clean code 서적에서도 확인할 수 있습니다.
부정 조건을 사용하는 경우 결과적으로 여러 번 생각하게 되기 때문입니다.
해당 부분 또한 분리하여 가독성을 가져가는 것도 보다 clean 한 code 를 만들 수 있는 방법이라 생각합니다

2022-11-16 14:45 UTC, jinsu4755 commented on app/src/main/java/org/sopt/sample/presentation/login/signup/SignUpActivity.kt
> +    }
checkInput 의 경우 여러 LiveData의 이벤트를 한번에 처리하는 것으로 알고 있습니다.
그렇다면 결과적으로 이 이벤트를 이용해 외부 상태를 변경하고 이용하기 보다 자체 이벤트를 직접 이용하는 방식을 사용하는 것이 더 좋지 않을까요?
해당 부분으로 결국 뷰에서 처리해야만 하는 로직이 발생하였고 결과적으로 뷰에서 뷰모델로 뷰의 상태와 이벤트를 분리하지 못하는 결과가 발생한 것 같습니다

2022-11-16 14:45 UTC, jinsu4755 commented on app/src/main/java/org/sopt/sample/presentation/login/signup/SignUpActivity.kt
> +        }
위 observeCheckInput 의 이유로 결과적으로 뷰에서 발생하는 이벤트를 뷰모델에서 처리하지 못하고 있다고 생각합니다.
printState 에서 stateMessage 의 변경을 하는 역할이 현재 분리한 역할에 들어가야 하는 이유가 있을까요?

2022-11-16 14:45 UTC, jinsu4755 commented on app/src/main/java/org/sopt/sample/presentation/login/signup/SignUpViewModel.kt
> +    }
MediatorLiveData 의 경우 저도 잘 몰랐는데 덕분에 이렇게 사용하는 케이스도 있구나 하고 알고 갑니다 :)
다만, chekInput 이라는 상태의 이름은 확장의 있어서 오해를 불러올 수 있을 것 같습니다.
만약 필수가 아닌 입력을 받아야 하는 상태가 추가된다면 해당 뷰모델을 유지보수 하는 사람이 코드를 접한다면 checkInput 은 모든 Input을 체크한다 혹은 어떤 Input 에 대한 것을 체크하는지 해당 코드를 읽고 이해하지 않는다면 알 수 없을 것 같습니다.
이름이 길더라도 그 뜻이 명확한 것이 중요하다고 생각합니다.
또한 해당 property의 경우 무언가를 검증한 결과를 담는 상태보다는 현재 입력 값에 대해 보여줘야만 하는 상태라고 이해했습니다.
따라서 "필수 값을 입력했는가?에 대한 반환 메시지"를 담는 상태의 이름을 지어준다면 보다 명확하고 해당 property의 사용을 직접 확인하지 않더라도 동작을 이해할 수 있을 것 같습니다

2022-11-16 15:28 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/presentation/login/signup/SignUpViewModel.kt
> +    }
> 또한 부정 조건을 피하라는 말은 clean code 서적에서도 확인할 수 있습니다.

하나의 방향성으로 사고의 방향을 단순화하여 가독성을 높이는 방향에 대해서는 동의합니다!

2022-11-16 15:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/presentation/login/signup/SignUpViewModel.kt
> +    }
이 부분에서 조금 더 첨언을 해보자면, 이메일의 입력값과 패스워드의 입력값 따로따로 검증을 필요로하고 각자 다른 에러 문구를 띄울 수 있습니다. 이와 같이 설계를 할 경우에는 각 입력값에서 어떤 에러가 났는지에 대해서는 명확히 검증을 하기가 힘들 수 있을 것 같습니다!

2022-11-16 15:31 UTC, l2hyunwoo commented
@jinsu4755 다른 파트원분들에게도 천금과 같은 리뷰를 하사해주십쇼 28기 파트장님

2022-11-16 15:34 UTC, jinsu4755 commented
> @jinsu4755 다른 파트원분들에게도 천금과 같은 리뷰를 하사해주십쇼 28기 파트장님

아니 왜 코드 주인이 아니라 엉뚱한 파트장님께서 나타나셨습니까..?
![image](https://user-images.githubusercontent.com/45380072/202223846-6f012067-a77d-403d-96cf-3c9edbc6086e.png)

2023-05-19 05:15 UTC, merged